services:
  mi-mongo:
    image: mongo
    volumes:
      - mongo-vol:/data/db
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.10
    expose:
      - "27017"

  mi-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-node-image
    depends_on:
      - mi-mongo
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.11
      node-nginx-net:
        ipv4_address: 172.80.0.10
    expose:
      - "3000"

  mi-nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - mi-node
    networks:
      node-nginx-net:
        ipv4_address: 172.80.0.11
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  mongo-node-net:
    ipam:
      config:
        - subnet: 172.40.0.0/16
  node-nginx-net:
    ipam:
      config:
        - subnet: 172.80.0.0/16

volumes:
  mongo-vol:
